#!/usr/bin/env zsh

source $DOTFILES/aliases.sh

if [[ $(hostname) == 'spider.casraf.dev' ]]; then
  text='@spider'
  extra_echo=1
else
  text='casraf'
fi

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

ascii-text -B -c rainbow $text

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

