#!/usr/bin/env zsh

source $DOTFILES/aliases.sh

# logo='
#                                                    /$$$$$$
#                                                   /$$__  $$
#   /$$$$$$$  /$$$$$$   /$$$$$$$  /$$$$$$  /$$$$$$ | $$  \__/
#  /$$_____/ |____  $$ /$$_____/ /$$__  $$|____  $$| $$$$
# | $$        /$$$$$$$|  $$$$$$ | $$  \__/ /$$$$$$$| $$_/
# | $$       /$$__  $$ \____  $$| $$      /$$__  $$| $$
# |  $$$$$$$|  $$$$$$$ /$$$$$$$/| $$     |  $$$$$$$| $$
#  \_______/ \_______/|_______/ |__/      \_______/|__/
# '

# echo "$(tput bold)$(echo $logo)$(tput sgr0)" | lolcat -f
# echo
# echo

if [[ $(hostname) == 'spider.casraf.dev' ]]; then
  text='@spider'
  extra_echo=1
else
  text='casraf'
fi

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

ascii-text -B -c rainbow $text

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

