#!/usr/bin/env zsh

source $DOTFILES/aliases.sh

# logo='
#                                                    /$$$$$$
#                                                   /$$__  $$
#   /$$$$$$$  /$$$$$$   /$$$$$$$  /$$$$$$  /$$$$$$ | $$  \__/
#  /$$_____/ |____  $$ /$$_____/ /$$__  $$|____  $$| $$$$
# | $$        /$$$$$$$|  $$$$$$ | $$  \__/ /$$$$$$$| $$_/
# | $$       /$$__  $$ \____  $$| $$      /$$__  $$| $$
# |  $$$$$$$|  $$$$$$$ /$$$$$$$/| $$     |  $$$$$$$| $$
#  \_______/ \_______/|_______/ |__/      \_______/|__/
# '

# echo "$(tput bold)$(echo $logo)$(tput sgr0)" | lolcat -f
# echo
# echo

text=$([[ hostname == 'spider.casraf.dev' ]] && echo '@spider' || echo 'casraf')

ascii-text -B -c rainbow $text
