general:
  root: ~/Dev

df:
  name: dotfiles
  root: ~/.dotfiles
  windows:
    - .
    - utils

dotfiles:
  name: dotfiles
  root: ~/.dotfiles
  windows:
    - .
    - utils
# df:
#   name: dotfiles
#   root: ~/.dotfiles
#   windows:
#     - .
#     - utils
#
# dotfiles:
#   name: dotfiles
#   root: ~/.dotfiles
#   windows:
#     - .
#     - utils
