.config:
  projects_path: ~/Dev

general:
  root: ~/Dev

df:
  name: dotfiles
  root: ~/.dotfiles
  windows:
    - .
    - utils

dotfiles:
  name: dotfiles
  root: ~/.dotfiles
  windows:
    - .
    - utils
