.\" Manpage for home
.TH man 7 "31 Jan 2021" "1.0" "home man page"
.SH NAME
home \- dotfiles manager
.SH SYNOPSIS
home [COMMAND]
.P
rhome [COMMAND]
.SH DESCRIPTION
home is a command for managing dotfiles across the system.
.P 
rhome is a complementary command that runs 
.I "home reload"
before running the supplied command
.SH OPTIONS
home takes one command:

    git             Run arbitrary git commands from .dotfiles directory

    brew            Subcommands: dump, install.
                    Use brew bundle to load or dump currently installed packages. 
                    Will read/write from Brewfile in .dotfiles directory

    push            Add all files, commit and push updates to git

    pull            Pull updates from git and reload

    reload, rl      Reload (source) the current shell

    refresh, rr     Refresh (source) only the home script

    install         Install all settings files to their appropriate locations 
                    (e.g. iTerm profiles file, MAN pages)

    help, -h        Dislpay help file

.SH BUGS
See https://github.com/chenasraf/dotfiles/issues
.SH AUTHOR
Chen Asraf (contact@casraf.com)
