.\" Manpage for home.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 7 "31 Jan 2021" "1.0" "home man page"
.SH NAME
home \- dotfiles manager
.SH SYNOPSIS
home [COMMAND]
.P
rhome [COMMAND]
.SH DESCRIPTION
home is a command for managing dotfiles across the system.
.P 
rhome is a complementary command that runs 
.I "home reload"
before running the supplied command
.SH OPTIONS
home takes one command:

    push            Push updates to git

    pull            Pull updates from git

    reload, rl      Reload (source) the current shell

    refresh, rr     Refresh (source) only the home script

    install         Install all settings files to their appropriate locations (e.g. iTerm profiles file, MAN pages)

    help, -h        Dislpay help file

.SH BUGS
See https://github.com/chenasraf/dotfiles/issues
.SH AUTHOR
Chen Asraf (contact@casraf.com)
