.\" Manpage for home
.TH man 7 "2 Sep 2022" "1.0" "home man page"
.SH NAME
home \- dotfiles manager
.SH SYNOPSIS
home [COMMAND]
.P
rhome [COMMAND]
.SH DESCRIPTION
home is a command for managing dotfiles across the system.
.P 
rhome is a complementary command that runs 
.I "home reload"
before running the supplied command
.SH OPTIONS

home takes one command:

git, g              Run arbitrary git commands from .dotfiles directory

worflows, w         Manage custom workflows for Alfred, keeping them in sync between dotfiles and external repository
                    (if applicable).
                    - Sub commands available: push, pull

motd, m             Manage syncd MOTD (Message of the Day)
                    - Sub commands available: restore, backup, edit, show

brew, b             Use brew bundle to load or dump currently installed packages. 
                    Will read/write from Brewfile in .dotfiles directory
                    - Subcommands: dump, restore.

brew, b             Manage data for Dropzone installation.
                    - Subcommands: dump, restore.

status, s           See git status for dotfiles directory

push, p             Add all files, commit and push updates to git. Supply commit msg as first arg or it will ask
                    interactively.

pull, l             Pull updates from git and reload home

reload-term, rt     Reload (source) the current ZSH shell. Incrementally slower as you use it in same terminal.

reload-home, rh     Reload (source) only the home script and tools. Faster than reload-term.

install, i          Install all settings files to their appropriate locations (e.g. MAN page, plugins, themes, bins, etc)

help, -h            Dislpay help file

.SH CUSTOM ALIASES

tpl                     Generate custom templates. See `tpl -h` for list

arm                     Run executable as ARM architecture

x86                     Run executable as x86 architecture

listening [port]        Check if [port] is being listened and by what process.
                        If no port is specified, all are listed.

.SH SHORTCUTS & ESCAPE SEQUENCES

ESC+man         Read MAN page of last command

ESC+ESC         Prepend sudo to last command

ALT+UP          Up one directory

ALT+DOWN        Open first alphabetical directory in current
.\" 
.\" ALT+LEFT        Previous directory
.\" 
.\" ALT+RIGHT       Next directory
.\" 
.SH AUTHOR
Chen Asraf <contact@casraf.dev>
