
script_runner:
  scripts:
    - build:apk: flutter build apk
    - name: get-version
      cmd: dart scripts/get_version.dart
      suppress_header_output: true
    - name: get-name
      cmd: dart scripts/get_name.dart
      suppress_header_output: true
    - push: 'version=$(get-version); name=$(get-name); echo "Pushing ${name}-$version.apk"; adb push build/app/outputs/flutter-apk/app-release.apk /sdcard/Download/${name}-${version}.apk'
    - install: adb install build/app/outputs/flutter-apk/app-release.apk
    - to-device: build:apk && push && install
    - auto-fix: dart fix --apply
    - format: flutter format -l 100 --fix lib/ test/

    - gen:page: npx simple-scaffold@latest -t templates/page -o lib/modules -s true
    - gen:model: npx simple-scaffold@latest -t templates/model -o lib/models -s false
    - gen:widget: npx simple-scaffold@latest -t templates/widget -o lib/widgets -s false
    - gen:icons: flutter pub run icons_launcher:create
