local mark = require('harpoon.mark')
local ui = require('harpoon.ui')

vim.keymap.set('n', '<leader>a', mark.add_file, { desc = "Add file to Harpoon" })
vim.keymap.set('n', '<C-H>', ui.toggle_quick_menu, { desc = "Toggle Harpoon Quick Menu" })
vim.keymap.set('n', '<C-1>', function() ui.nav_file(1) end, { desc = "Navigate to Harpoon mark 1" })
vim.keymap.set('n', '<C-2>', function() ui.nav_file(2) end, { desc = "Navigate to Harpoon mark 2" })
vim.keymap.set('n', '<C-3>', function() ui.nav_file(3) end, { desc = "Navigate to Harpoon mark 3" })
vim.keymap.set('n', '<C-4>', function() ui.nav_file(4) end, { desc = "Navigate to Harpoon mark 4" })
vim.keymap.set('n', '<C-5>', function() ui.nav_file(5) end, { desc = "Navigate to Harpoon mark 5" })
vim.keymap.set('n', '<C-6>', function() ui.nav_file(6) end, { desc = "Navigate to Harpoon mark 6" })
vim.keymap.set('n', '<C-7>', function() ui.nav_file(7) end, { desc = "Navigate to Harpoon mark 7" })
vim.keymap.set('n', '<C-8>', function() ui.nav_file(8) end, { desc = "Navigate to Harpoon mark 8" })
vim.keymap.set('n', '<C-9>', function() ui.nav_file(8) end, { desc = "Navigate to Harpoon mark 9" })
vim.keymap.set('n', '<C-0>', function() ui.nav_file(10) end, { desc = "Navigate to Harpoon mark 10" })

