tap "chenasraf/tap"
tap "dotenvx/brew"
tap "homebrew/bundle"
tap "jesseduffield/lazygit"
# Load/unload environment variables based on $PWD
brew "direnv"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git extension for versioning large files
brew "git-lfs"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Rainbows and unicorns in your console!
brew "lolcat"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Generic syntax highlighter
brew "pygments"
# Ruby version manager
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Opinionated Lua code formatter
brew "stylua"
# Terminal multiplexer
brew "tmux"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Gitignore generator for any type of project
brew "chenasraf/tap/gi_gen"
# Outputs a Tree-like representation from strings
brew "chenasraf/tap/treelike"
# Better dotenv–from the creator of `dotenv`
brew "dotenvx/brew/dotenvx"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# Command-line interface for 1Password
cask "1password-cli"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm@nightly"

