#!/usr/bin/env zsh

source "$DOTFILES/aliases.zsh"
source $DOTFILES/plugins/ascii_font/ascii_font.plugin.zsh

if [[ $(hostname) == 'spider.casraf.dev' ]]; then
  text='@spider'
  extra_echo=1
else
  text='casraf'
fi

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

ascii-text -W -B -c rainbow $text

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

unset -f ascii-text
