#!/usr/bin/env zsh

source "$DOTFILES/aliases.zsh"
ascii-text() { . $DOTFILES/plugins/ascii_font/ascii_font.zsh }

if [[ $(hostname) == 'spider.casraf.dev' ]]; then
  text='@spider'
  extra_echo=1
else
  text='casraf'
fi

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

ascii-text -B -c rainbow $text

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

unset -f ascii-text
