#!/usr/bin/env zsh

updfile="$HOME/.cache/.df_last_update"
touch $updfile
lastupdate=$(cat $updfile)
if [[ -z $lastupdate ]]; then
  lastupdate=0
fi

# 1 day
timeout=86400
if [[ $(date +%s) -gt $((lastupdate + $timeout)) ]]; then
  echo_yellow "Checking for updates..."
  git -C "$HOME/.dotfiles" fetch
  echo $(date +%s) > $updfile
fi

loc=$(git -C $HOME/.dotfiles rev-parse HEAD)
rem=$(git -C $HOME/.dotfiles rev-parse @{u})

if [[ $loc != $rem ]]; then
  echo_yellow "You have home updates waiting to be pulled/pushed."
  echo_yellow "Use \`hp\` to push the local changes, or \`hli\` to pull & install the remote changes."
  echo_yellow "Git status:\n"
  git -C $HOME/.dotfiles status
  echo
fi
