#!/usr/bin/env zsh

source "$HOME/.dotfiles/plugins/colors.plugin.zsh"

local=$(git -C $HOME/.dotfiles rev-parse HEAD)
remote=$(git -C $HOME/.dotfiles rev-parse @{u})

if [[ $local != $remote ]]; then
  echo_yellow "You have home updates waiting to be pulled/pushed."
  echo_yellow "Use \`hp\` to push the local changes, or \`hli\` to pull & install the remote changes."
  echo_yellow "Git status:\n"
  git -C $HOME/.dotfiles status
  echo
fi
