return {{[ [[top]] ] = {2},[ [[bottom]] ] = {3},[ [[windows]] ] = {4},[ [[right]] ] = {5},[ [[left]] ] = {6},[ [[sides]] ] = {7},},
{[ [[w]] ] = 1300,[ [[h]] ] = 50,},
{[ [[w]] ] = 1300,[ [[h]] ] = 50,},
{[ [[bottomRightContainer]] ] = {8},[ [[bottomContainer]] ] = {9},[ [[topRightContainer]] ] = {10},},
{[ [[w]] ] = 1082,[ [[h]] ] = 725,},
{[ [[w]] ] = 50,[ [[h]] ] = 196,},
{[ [[top]] ] = [[enabled]],[ [[right]] ] = [[enabled]],[ [[left]] ] = [[enabled]],[ [[bottom]] ] = [[enabled]],},
{[1] = {11},[2] = {12},[3] = {13},[4] = {14},[5] = {15},[6] = {16},[7] = {17},[8] = {18},},
{[1] = [[Gauges]],},
{[1] = {19},},
{[1] = [[All]],[2] = true,},
{[1] = [[Private]],[2] = true,},
{[1] = [[Group]],[2] = true,},
{[1] = [[Tell]],[2] = true,},
{[1] = [[Say]],[2] = true,},
{[1] = [[Spouse]],[2] = true,},
{[1] = [[Clan]],[2] = true,},
{[1] = [[Friend]],[2] = true,},
{[1] = [[Map]],[2] = true,},
}